triggers:
- description: null
  envs: []
  last_enabled_at: 2024-07-09 08:59:42.189497+00:00
  name: retrain models hourly
  pipeline_uuid: automatic_retraining
  schedule_interval: '@hourly'
  schedule_type: time
  settings:
    allow_blocks_to_fail: true
    create_initial_pipeline_run: true
    skip_if_previous_running: true
  sla: null
  start_time: 2024-07-08 21:00:00+00:00
  status: active
  token: ed63cef96eac4aeabff651a86bc1a579
  variables: {}
